<a href="https://colab.research.google.com/github/kmberg-kopecky/capstone/blob/main/complete_final_final_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Decision Tree Regression

## Importing the libraries

In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import metrics

url = 'https://raw.githubusercontent.com/kmberg-kopecky/capstone/main/mushroom_data_final.csv'
dataset = pd.read_csv(url)

#dataset = pd.read_csv(https://github.com/kmberg-kopecky/capstone/blob/main/mushroom_data_final.csv)


#from google.colab import files

#uploaded = files.upload()


## Importing the dataset

In [16]:
#from google.colab import drive
#drive.mount('/content/drive')


In [17]:
#dataset = pd.read_csv('/content/drive/MyDrive/final proj/mushroom data final.csv')
#dataset = pd.read_csv(io.BytesIO(uploaded['mushroom data final.csv']))

In [18]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
dataset['cap-shape'] = label_encoder.fit_transform(dataset['cap-shape'])
dataset['cap-shape'].unique()
print(dataset['cap-shape'])

# 0 -> b = bell
# 1 -> f = flat
# 2 -> s = sunken
# 3 -> x = convex

0      3
1      3
2      0
3      3
4      3
      ..
244    1
245    3
246    3
247    3
248    1
Name: cap-shape, Length: 249, dtype: int64


In [19]:
label_encoder = LabelEncoder()
dataset['cap-surface'] = label_encoder.fit_transform(dataset['cap-surface'])
dataset['cap-surface'].unique()
print(dataset['cap-surface'])

# 0 -> f = fibrous
# 1 -> s = smooth
# 2 -> y = scaly
label_encoder = LabelEncoder()
dataset['cap-color'] = label_encoder.fit_transform(dataset['cap-color'])
dataset['cap-color'].unique()
print(dataset['cap-color'])

# 0 -> g = grey
# 1 -> n = brown
# 2 -> w = white
# 3 -> y = yellow
label_encoder = LabelEncoder()
dataset['odor'] = label_encoder.fit_transform(dataset['odor'])
dataset['odor'].unique()
print(dataset['odor'])

# 0 -> a = almond
# 1 -> l = anise
# 2 -> n = none
# 3 -> p = pungent

0      1
1      1
2      1
3      2
4      1
      ..
244    0
245    1
246    1
247    2
248    2
Name: cap-surface, Length: 249, dtype: int64
0      1
1      3
2      2
3      2
4      0
      ..
244    2
245    2
246    2
247    2
248    3
Name: cap-color, Length: 249, dtype: int64
0      3
1      0
2      1
3      3
4      2
      ..
244    0
245    1
246    1
247    0
248    1
Name: odor, Length: 249, dtype: int64


In [20]:
label_encoder = LabelEncoder()
dataset['gill-spacing'] = label_encoder.fit_transform(dataset['gill-spacing'])
dataset['gill-spacing'].unique()
print(dataset['gill-spacing'])

# 0 -> c = close
# 1 -> w = crowded
label_encoder = LabelEncoder()
dataset['gill-color'] = label_encoder.fit_transform(dataset['gill-color'])
dataset['gill-color'].unique()
print(dataset['gill-color'])


# 0 -> g = grey
# 1 -> h = chocolate
# 2 -> k = black
# 3 -> n = brown
# 4 -> p = pink
# 5 -> w = white

label_encoder = LabelEncoder()
dataset['stalk-shape'] = label_encoder.fit_transform(dataset['stalk-shape'])
dataset['stalk-shape'].unique()
print(dataset['stalk-shape'])

# 0 -> e = enlarging
# 1 -> t = tapering

0      0
1      0
2      0
3      0
4      1
      ..
244    1
245    0
246    1
247    0
248    0
Name: gill-spacing, Length: 249, dtype: int64
0      2
1      2
2      3
3      3
4      2
      ..
244    4
245    5
246    4
247    3
248    5
Name: gill-color, Length: 249, dtype: int64
0      0
1      0
2      0
3      0
4      1
      ..
244    1
245    0
246    1
247    0
248    0
Name: stalk-shape, Length: 249, dtype: int64


In [21]:
label_encoder = LabelEncoder()
dataset['population'] = label_encoder.fit_transform(dataset['population'])
dataset['population'].unique()
print(dataset['population'])

# 0 -> a = abundant
# 1 -> n = numerous
# 2 -> s = scattered
# 3 -> v = several
# 4 -> y = solitary

label_encoder = LabelEncoder()
dataset['habitat'] = label_encoder.fit_transform(dataset['habitat'])
dataset['habitat'].unique()
print(dataset['habitat'])

# 0 -> d = woods
# 1 -> g = grasses
# 2 -> m = meadows
# 3 -> p = paths
# 4 -> u = urban

label_encoder = LabelEncoder()
dataset['class'] = label_encoder.fit_transform(dataset['class'])
dataset['class'].unique()
print(dataset['class'])

# 0 -> e = edible
# 1 -> p = poisonous



0      2
1      1
2      1
3      2
4      0
      ..
244    3
245    2
246    3
247    2
248    4
Name: population, Length: 249, dtype: int64
0      4
1      1
2      2
3      4
4      1
      ..
244    0
245    1
246    0
247    2
248    3
Name: habitat, Length: 249, dtype: int64
0      1
1      0
2      0
3      1
4      0
      ..
244    0
245    0
246    0
247    0
248    0
Name: class, Length: 249, dtype: int64


In [22]:
#from google.colab import drive
#drive.mount('/content/drive')

## Training the Decision Tree Regression model on the whole dataset

In [23]:
x = dataset.iloc[:, 0:9].values
y = dataset.iloc[:, 9].values

In [24]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(x,y)



DecisionTreeRegressor(random_state=0)

## Predicting a new result

In [25]:
#Test with unseen data
#Answer should be 0

regressor.predict([[3,2,2,0,0,3,0,2,1]])

array([0.])

In [26]:
#Test with unseen data
#Answer should be 0

regressor.predict([[0,1,3,1,0,5,0,1,2]])

array([0.])

In [27]:
#Test with unseen data
#Answer should be 0

regressor.predict([[3,1,3,0,0,5,0,1,1]])

array([0.])

In [28]:
#Test with unseen data
#Answer should be 0

regressor.predict([[0,2,3,0,0,0,0,1,1]])

array([0.])

In [29]:
#Test with unseen data
#Answer should be 0

regressor.predict([[3,2,2,0,0,3,0,2,1]])

array([0.])

In [30]:
#Test with unseen data
#Answer should be 0

regressor.predict([[3,1,2,1,0,0,0,1,2]])

array([0.])

In [31]:
#Test with unseen data
#Answer should be 0

regressor.predict([[0,1,3,0,0,5,0,2,2]])

array([0.])

In [32]:
#Test with unseen data
#Answer should be 0

regressor.predict([[0,2,3,0,0,5,0,2,1]])

array([0.])

In [33]:
#Test with unseen data
#Answer should be 1
regressor.predict([[3,1,1,3,0,3,0,3,1]])

array([1.])

In [34]:
#Test with unseen data
#Answer should be 1

regressor.predict([[3,2,1,3,0,2,0,2,4]])

array([1.])

In [35]:
#Test with unseen data
#Answer should be 1

regressor.predict([[3,1,1,3,0,2,0,3,4]])

array([1.])

In [ ]:
input1 = input("What is the cap shape?\n 0 -> bell\n 1 -> flat\n 2 -> sunken\n 3 -> convex:")

input2 = input("What is the cap surface?\n 0 -> fibrous\n 1 -> smooth\n 2 -> scaly:")

input3 = input("What is the cap color?\n 0 -> grey\n 1 -> brown\n 2 -> white\n 3 -> yellow:")

input4 = input("What is the odor?\n 0 -> almond\n 1 -> anise\n 2 -> none\n 3 -> pungent:")

input5 = input("What is the gill spacing?\n 0 -> close\n 1 -> crowded:")

input6 = input("What is the gill color?\n 0 -> grey\n 1 -> chocolate\n 2 -> black\n 3 -> brown\n 4 -> pink\n 5 -> white:")

input7 = input("What is the stalk shape?\n 0 -> enlarging\n 1 -> tapering:")

input8 = input("What is the population?\n 0 -> abundant\n 1 -> numerous\n 2 -> scattered\n 3 -> several\n 4 -> solitary:")

input9 = input("What is the habitat?\n 0 -> woods\n 1 -> grasses\n 2 -> meadows\n 3 -> paths\n 4 -> urban:")


new_row = pd.DataFrame([[input1, input2, input3, input4, input5, input6, input7, input8, input9]], columns=['cap-shape','cap-surface','cap-color','odor','gill-spacing','gill-color','stalk-shape','population','habitat']) # Create a new DataFrame from the input
dataset = pd.concat([dataset, new_row], ignore_index=True) # Concatenate the new row to the existing DataFrame


print(dataset)

In [ ]:
if(regressor.predict([[input1, input2, input3, input4, input5, input6, input7, input8, input9]])==1):
  print("Poisonous")
else:
  print("Edible")